# control_node:
#   hosts:
#     localhost:
#       ansible_connection: local

servers:
  hosts:
    starlord:
      ansible_host: starlord
      ip: 192.168.86.95
      port: 8006
      primary_user: root
      local_proxy: {"https": true}

    stark:
      ansible_host: stark
      ip: 192.168.86.93
      port: 8006
      primary_user: root
      proxmox_notifications: true
      local_proxy: {"https": true}

    loki:
      ansible_host: loki
      ip: 192.168.86.97
      port: 8006
      primary_user: root
      local_proxy: {"https": true}

    pbs:
      ansible_host: pbs
      ip: 192.168.86.102
      port: 8007
      primary_user: root
      pve_host: starlord
      pve_id: 102
      local_proxy: {"https": true}

    immich:
      ansible_host: immich
      ip: 192.168.86.115
      port: 2283
      primary_user: root
      samba_shares: [{"name":"root", "path":"/root", "comment":"root folder"}, {"name":"opt", "path":"/opt", "comment":"opt directory", "root":true}]
      docker_compose_dirs: ["/opt/server/immich"]
      pve_host: starlord
      pve_id: 115
      reverse_proxy: {"subdomain":"immich", "port":"2283"}

    audiobookshelf:
      ansible_host: audiobookshelf
      ip: 192.168.86.105
      port: 13378
      primary_user: root
      pve_host: starlord
      pve_id: 105
      reverse_proxy: {"subdomain":"audiobooks", "port":"13378"}

    dockge:
      ansible_host: dockge
      ip: 192.168.86.112
      port: 5001
      primary_user: root
      pve_host: stark
      pve_id: 112
      local_proxy: {}

    karakeep:
      ansible_host: karakeep
      ip: 192.168.86.130
      port: 3000
      primary_user: root
      pve_host: stark
      pve_id: 130
      reverse_proxy: {"subdomain":"keep", "port":"3000"}

    paperless-ngx:
      ansible_host: paperless-ngx
      ip: 192.168.86.126
      port: 8000
      primary_user: root
      pve_host: stark
      pve_id: 126
      local_proxy: {}
    
    ollama:
      ansible_host: ollama
      ip: 192.168.86.113
      primary_user: root
      pve_host: stark
      pve_id: 113

    bitcoin:
      ansible_host: bitcoin
      ip: 192.168.86.103
      port: 8080
      primary_user: root
      docker_compose_dirs: ["/opt/docker"]
      pve_host: loki
      pve_id: 103
    
    truenas:
      ansible_host: truenas
      ip: 192.168.86.99
      primary_user: admin
      ansible_remote_tmp: /var/tmp/admin
      local_proxy:
        - {"https": true}
        - {"subdomain":"syncthing", "port":"20910"}

    wakanda:
      ansible_host: wakanda
      primary_user: root
      proxmox_notifications: true
      tailscale_routes: "10.10.12.0/24"

    bucky:
      ansible_host: bucky
      #ip: 100.124.132.103
      primary_user: admin
      ansible_remote_tmp: /var/tmp/admin

cluster_nodes:
  hosts:
    starlord:
    stark:
    loki:
    

remote_cluster_nodes:
  hosts:
    wakanda:

truenas_machines:
  hosts:
    truenas_home:
    bucky:
    